version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Gluetun-switcher
    restart: unless-stopped
    ports:
      # Accédez à l'application via http://localhost:3003
      - "3003:3003"
    environment:
      # Chemin où se trouvent les fichiers .conf à l'intérieur du conteneur
      - WIREGUARD_DIR=/etc/wireguard
      # Nom(s) du ou des conteneur(s) à redémarrer, séparés par une virgule
      - CONTAINER_TO_RESTART=gluetun,qbittorrent
    volumes:
      # Persistance des données de l'application (historique, etc.)
      - /volume1/docker/gluetun-switcher/config:/root/.config
      
      # --- VOLUME A ADAPTER PAR L'UTILISATEUR ---
      # Montez ici le dossier contenant vos configurations WireGuard de l'hôte.
      - /volume1/docker/gluetun/wireguard:/etc/wireguard

      # Montage du socket Docker pour permettre le redémarrage de conteneurs
      - /var/run/docker.sock:/var/run/docker.sock
